# -*- coding: utf-8 -*-
"""4110E016_10/11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AjJ3lgkUrZ-J8yB00x1DtVMRKJZgeZoz
"""

a = 33
b = 200

if b > a:
    print("b is greater than a")

a = 33
b = 20

if b > a:
  print("b is greater than a")

a = 32
b = 33

if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")

a = 33
b = 33
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")

a = 35
b = 33

if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")

a = 200
b = 33

if b > a:
  print("b is greater than a")
else:
  print("b is not greater than a")

a = 200
b = 33

if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
else:
  print("a is greater than b")

year= eval(input("請輸入年"))

if ((year%400==0) or (year%4==0 and year%100!=0)):
  print("{0} 是閏年".format(year))
else:
  print("{0} 不是閏年".format(year))